name: Build and Publish

on:
  workflow_dispatch:
    inputs:
      major_release:
        description: 'Is it a major release?'
        required: false
        default: false
        type: boolean
      minor_release:
        description: 'Is it a minor release?'
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main

jobs:
  increment_version:
    runs-on: ubuntu-latest
    if: github.actor == 'github-actions[bot]'
    outputs:
      version: ${{ steps.increment_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Increment version
        id: increment_version
        run: |
          version_type="patch"

          if [ "${{ github.event.inputs.major_release }}" == "true" ]; then
              version_type="major"
          elif [ "${{ github.event.inputs.minor_release }}" == "true" ]; then
              version_type="minor"
          fi

          chmod +x increment_version.sh
          VERSION=$(./increment_version.sh $version_type)
          echo "The version here: $VERSION;"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
  

  build:
    runs-on: ubuntu-latest
    needs: increment_version
    if: github.actor == 'github-actions[bot]'
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update VERSION file
        run: |
          VERSION=${{ needs.increment_version.outputs.version }}
          echo "New version should be: $VERSION"
          echo "$VERSION" > "VERSION"
      

      - name: Commit and push updated VERSION file
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@example.com"
          git add .
          git commit -m "Update version to ${{ needs.increment_version.outputs.version }} [skip ci]"
          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/QuizU-SevastianBahynskyi/quizu-schema.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Gradle
        run: chmod +x gradle/gradlew && cd gradle && ./gradlew build
        env:
          VERSION: ${{ needs.increment_version.outputs.version }}

      - name: Release maven package
        env:
          GITHUB_TOKEN: ${{ secrets.QUIZ_GITHUB_PACKAGES_TOKEN }}
          GITHUB_ACTOR: ${{ github.QUIZ_GITHUB_ACTOR }}
          VERSION: ${{ needs.increment_version.outputs.version }}
        run: chmod +x gradle/gradlew && cd gradle && ./gradlew publish
